"""Patient education copy. Edit here, then run scripts/build_site.py."""
UPDATED = '2026-09-08'
SOURCES = {
 'palpitations': ('NHS: Heart palpitations (2026)', 'https://www.nhs.uk/symptoms/heart-palpitations/'),
 'palpitations_tests': ('Mayo Clinic: Heart palpitations - diagnosis and treatment', 'https://www.mayoclinic.org/diseases-conditions/heart-palpitations/diagnosis-treatment/drc-20373201'),
 'arrhythmia_tests': ('NHLBI: Diagnosing arrhythmias', 'https://www.nhlbi.nih.gov/health/arrhythmias/diagnosis'),
 'arrhythmia_types': ('NHLBI: Types of arrhythmias', 'https://www.nhlbi.nih.gov/health/arrhythmias/types'),
 'af_diagnosis': ('ACC/AHA/ACCP/HRS: 2023 AF guideline - confirming the rhythm diagnosis', 'https://www.jacc.org/doi/10.1016/j.jacc.2023.08.017'),
 'bpweek': ('AHA: How to measure blood pressure at home (2022)', 'https://www.heart.org/en/news/2022/05/23/monitoring-blood-pressure-at-home-can-be-tricky-heres-how-to-do-it-right'),
 'bp': ('AHA: Home Blood Pressure Monitoring (2025)', 'https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings/monitoring-your-blood-pressure-at-home'),
 'bp25': ('ACC/AHA: 2025 High Blood Pressure Guideline overview', 'https://www.acc.org/About-ACC/Press-Releases/2025/08/13/20/03/New-high-blood-pressure-guideline-emphasizes-prevention-early-treatment-to-reduce-CVD-risk'),
 'lipid26': ('ACC/AHA: 2026 Guideline on the Management of Dyslipidemia', 'https://www.acc.org/latest-in-cardiology/journal-scans/2026/03/13/15/20/acc-aha-release-new-clinical-guideline-for-managing-dyslipidemia'),
 'lipidgoals': ('ACC/AHA: Individual cholesterol goals and additional risk testing (2026)', 'https://www.acc.org/about-acc/press-releases/2026/03/13/18/01/accaha-issue-updated-guideline-for-managing-lipids-cholesterol'),
 'samson': ('Howard JP, et al. Side Effect Patterns in a Crossover Trial of Statin, Placebo, and No Treatment. JACC. 2021;78:1210-1222.', 'https://www.jacc.org/doi/10.1016/j.jacc.2021.07.022'),
 'intolerance': ('ACC: NLA 2022 Definition of Statin Intolerance', 'https://www.acc.org/latest-in-cardiology/articles/2022/08/08/12/27/nla-2022-definition-of-statin-intolerance'),
 'aspirin': ('ACC: Aspirin for primary prevention and bleeding risk (2022)', 'https://www.acc.org/latest-in-cardiology/articles/2022/04/27/20/41/new-uspstf-recommendation-on-aspirin-in-cvd'),
 'cacaspirin': ('ACC: Coronary calcium and estimated net benefit of aspirin (2020)', 'https://www.acc.org/Latest-in-Cardiology/Journal-Scans/2020/10/30/15/38/Value-of-Coronary-Artery-Calcium-Scanning'),
 'cac': ('ACR/RSNA RadiologyInfo: Cardiac CT for Calcium Scoring', 'https://www.radiologyinfo.org/en/info/ct_calscoring'),
 'cta': ('ACR/RSNA RadiologyInfo: Coronary CTA', 'https://www.radiologyinfo.org/en/info/angiocoroct'),
 'echo': ('AHA: Echocardiogram (2025)', 'https://www.heart.org/en/health-topics/heart-attack/diagnosing-a-heart-attack/echocardiogram'),
 'ef': ('AHA: Ejection Fraction and Heart Failure (2025)', 'https://www.heart.org/en/health-topics/heart-failure/diagnosing-heart-failure/ejection-fraction-heart-failure-measurement'),
 'valvetests': ('AHA: Heart Valve Disease Diagnosis and Testing (2026)', 'https://www.heart.org/en/health-topics/heart-valve-problems-and-disease/getting-an-accurate-heart-valve-diagnosis'),
 'hf': ('ACC: 2022 AHA/ACC/HFSA Heart Failure Guideline', 'https://www.acc.org/Latest-in-Cardiology/ten-points-to-remember/2022/03/29/19/53/2022-AHA-ACC-HFSA-Heart-Failure-Guideline-gl-hf'),
 'hfpatient': ('AHA: Heart Failure Explained', 'https://www.heart.org/en/health-topics/heart-failure/heart-failure-explained'),
 'af': ('ACC: 2023 Guideline for Diagnosis and Management of Atrial Fibrillation', 'https://www.acc.org/latest-in-cardiology/ten-points-to-remember/2023/11/27/19/46/2023-acc-guideline-for-af-gl-af'),
 'holter': ('AHA: Holter Monitor (2025)', 'https://www.heart.org/en/health-topics/arrhythmia/symptoms-diagnosis--monitoring-of-arrhythmia/holter-monitor'),
 'event': ('AHA: Cardiac Event Recorder', 'https://www.heart.org/en/health-topics/arrhythmia/symptoms-diagnosis--monitoring-of-arrhythmia/cardiac-event-recorder'),
 'pvc': ('AHA: Premature Contractions - PACs and PVCs (2024)', 'https://www.heart.org/en/health-topics/arrhythmia/about-arrhythmia/premature-contractions-pacs-and-pvcs'),
 'zio': ('iRhythm: MyZio patient app and symptom logging', 'https://www.irhythmtech.com/us/en/solutions-services/irhythm-service/myzio-patient-app'),
 'stress': ('AHA: Exercise Stress Test (2025)', 'https://www.heart.org/en/health-topics/heart-attack/diagnosing-a-heart-attack/exercise-stress-test'),
 'nuclear': ('AHA: Myocardial Perfusion Imaging - PET and SPECT (2025)', 'https://www.heart.org/en/health-topics/heart-attack/diagnosing-a-heart-attack/myocardial-perfusion-imaging'),
 'cad': ('ACC: 2023 Guideline for Managing Chronic Coronary Disease', 'https://www.acc.org/Latest-in-Cardiology/ten-points-to-remember/2023/07/17/19/06/2023-guideline-for-chronic-coronary-disease-gl-ccd'),
 'valve': ('ACC: 2020 ACC/AHA Heart Valve Disease Guideline, Part 1', 'https://www.acc.org/latest-in-cardiology/ten-points-to-remember/2020/12/16/21/58/2020-acc-aha-vhd-gl-pt-1-gl-vhd'),
 'tavr': ('ACC: Choosing TAVI or surgical valve replacement (2021)', 'https://www.acc.org/Latest-in-Cardiology/ten-points-to-remember/2021/07/22/19/36/Guideline-Update-on-Indications-for-TAVI'),
 'eight': ('AHA: Life\'s Essential 8', 'https://www.heart.org/en/healthy-living/healthy-lifestyle/lifes-essential-8'),
 'activity': ('ACC: Exercise Benefits in Cardiovascular Disease (2023)', 'https://www.acc.org/Latest-in-Cardiology/ten-points-to-remember/2023/04/10/15/09/exercise-benefits-in-cvds'),
 'exerciseplan': ('AHA: Develop a Physical Activity Plan for You (2024)', 'https://www.heart.org/en/health-topics/cardiac-rehab/getting-physically-active/develop-a-physical-activity-plan-for-you'),
 'restart': ('MedlinePlus: Being active after your heart attack', 'https://medlineplus.gov/ency/patientinstructions/000093.htm'),
 'rehab': ('AHA: What Is Cardiac Rehabilitation? (2024)', 'https://www.heart.org/en/health-topics/cardiac-rehab/what-is-cardiac-rehabilitation'),
 'rehabeligible': ('AHA: Am I Eligible for Cardiac Rehab? (2024)', 'https://www.heart.org/en/health-topics/cardiac-rehab/am-i-eligible-for-cardiac-rehab'),
}

PAGES = []
def page(path, title, category, summary, sections, sources, questions, related=(), download=None, reviewed_by=None, reviewed_on=None, updated=None):
    PAGES.append(dict(path=path,title=title,category=category,summary=summary,sections=sections,sources=sources,questions=questions,related=related,download=download,reviewed_by=reviewed_by,reviewed_on=reviewed_on,updated=updated or UPDATED))

page('articles/palpitations.html', 'Palpitations', 'Symptoms and heart rhythm',
 'Understand racing, fluttering or skipped heartbeats, what testing can show, and when to get help.', [
 ('what-they-are','What are palpitations?', '''<p>Palpitations mean you notice your heartbeat more than usual. You may feel a flutter, thump, racing pulse, or a pause followed by a stronger beat. The feeling can occur in your chest, neck or throat, at rest or with activity.</p><p>Palpitations are a symptom, not a diagnosis. Many have a harmless explanation, but the sensation alone cannot tell us which rhythm is present. The goal of testing is to connect what you feel with what your heart is doing.</p>'''),
 ('when-to-seek-care','When to seek care', '''<div class="care-callout"><p><strong>Call 911 if palpitations occur with chest pain or pressure, shortness of breath, fainting, or severe dizziness or feeling that you may pass out.</strong> Do not drive yourself or wait for a monitor result. If an episode with these symptoms has stopped, seek urgent medical advice.</p></div><p>A new racing heartbeat that will not settle needs prompt assessment. Arrange a visit for episodes that recur, last longer or become more frequent, even if you otherwise feel well. Tell your clinician about known heart disease or a family history of serious rhythm problems or unexplained sudden death.</p>'''),
 ('causes','What can cause them?', '''<ul><li><strong>Everyday triggers:</strong> poor sleep, stress, exertion, nicotine, alcohol or excessive caffeine. Energy drinks, stimulant supplements and some cold medicines can also contribute.</li><li><strong>Other health conditions:</strong> anemia, thyroid problems, fever or changes in electrolytes may affect the heartbeat. Pregnancy and menopause can be associated with palpitations too.</li><li><strong>Early beats:</strong> PACs start in the upper heart chambers; PVCs start in the lower chambers. The pause and stronger beat afterward may feel like a skipped beat. Occasional early beats are common; their frequency and the condition of the heart matter.</li><li><strong>A rhythm problem:</strong> examples include <a href="afib.html">atrial fibrillation (AFib)</a> and supraventricular tachycardia (SVT). SVT is a fast rhythm arising above the lower heart chambers; episodes may begin and end abruptly.</li></ul><p>Stress can contribute, but new symptoms should not automatically be attributed to anxiety. <a href="#references">Sources and further reading</a>.</p>'''),
 ('first-visit','What happens at the first visit?', '''<p>Your clinician will ask how often episodes happen, how long they last, whether they start and stop suddenly, and whether they occur during exercise or rest. They will ask about associated symptoms, your medical and family history, and medicines or supplements. An examination and an ECG are common starting points.</p><p>Bring a short symptom record and your medication list, including nonprescription products. Testing is chosen to answer your particular question; not everyone needs every test below.</p>'''),
 ('testing','Which tests might I need?', '''<div class="table-scroll"><table><caption>Common tests for palpitations</caption><thead><tr><th scope="col">Test</th><th scope="col">What to expect and why it helps</th></tr></thead><tbody><tr><th scope="row">ECG / EKG</th><td>Sticky electrodes on the skin record the heart's electrical activity. This quick test shows the rhythm at that moment. A normal office ECG can miss an episode that happens at another time.</td></tr><tr><th scope="row"><a href="../tests/rhythm-monitor.html">Zio, Holter or event monitor</a></th><td>A wearable device records during everyday life so symptoms can be compared with the rhythm. The type and duration depend partly on how often symptoms occur.</td></tr><tr><th scope="row">Blood tests</th><td>Depending on the history, tests may look for anemia, a thyroid problem or an electrolyte imbalance. These look for contributors; they do not record the rhythm.</td></tr><tr><th scope="row"><a href="../tests/echocardiogram.html">Echocardiogram</a></th><td>Ultrasound checks heart muscle and valves when a structural problem is suspected or other findings make it useful. It answers a different question from an ECG.</td></tr><tr><th scope="row"><a href="../tests/stress-test.html">Exercise stress test</a></th><td>In selected cases, monitored exercise helps evaluate exertional symptoms or a concern about blood flow. It is not routine for every palpitation.</td></tr></tbody></table></div><p><a href="https://www.nhlbi.nih.gov/health/arrhythmias/diagnosis">NHLBI: how rhythm problems are diagnosed</a>.</p>'''),
 ('monitoring','What should I expect from a heart monitor?', '''<p>If symptoms happen daily, a shorter recording may capture them. If episodes are less frequent, a longer patch or event-monitor recording may be more useful. Some patches record for up to two weeks; other devices record longer. Rare but concerning events may call for a different approach, such as an implantable loop recorder, after discussion with a specialist.</p><p>Follow the instructions for your exact device, including showering, activity and returning it. Note the time of symptoms and what you were doing; press an event button if instructed. Ask about adhesive irritation and whom to contact if the device comes loose.</p><p>Ask when and how you will receive results. Some monitors are analyzed after return. Do not assume your device is watched continuously or that pressing its button requests emergency help. See the <a href="../tests/rhythm-monitor.html">rhythm-monitor guide</a>.</p>'''),
 ('results','What if the results are normal?', '''<p>A normal ECG or monitor result is useful information, but ask whether your usual symptoms occurred during the recording. A recording without an episode may not answer the original question. Your clinician may consider a different monitoring period if symptoms continue.</p><p>If your usual symptoms were recorded during a normal rhythm, that is helpful and often reassuring. If early beats or another rhythm were found, their amount, duration, symptoms and heart structure help determine the next step.</p><p>If you already have a watch or handheld ECG, ask whether sharing a saved tracing would help. An automated alert alone does not establish AFib; the ECG signal needs clinician review. Do not delay urgent care to capture a recording. <a href="https://www.jacc.org/doi/10.1016/j.jacc.2023.08.017">AF diagnosis guidance</a>.</p>'''),
 ('next-steps','What helps, and will I need treatment?', '''<p>Care depends on the cause. Some people need reassurance and follow-up; others need treatment for a contributing condition or rhythm problem. For troublesome early beats, a clinician may consider medication. Selected rhythm problems may benefit from an electrophysiology consultation or catheter ablation, but a procedure is not the usual starting point.</p><p>Prioritize sleep, avoid nicotine and stimulant drugs, and notice whether caffeine or alcohol tracks with symptoms. Discuss reducing a suspected trigger. Stay hydrated within any fluid limits your clinician has given you. Do not stop prescribed medicines or start potassium or magnesium supplements on your own.</p><p>Keep a brief record of the time, duration, activity and accompanying symptoms. If activity brings on symptoms, stop and ask about evaluation before increasing intensity. Agree on how to share your record, when results will be reviewed, and what changes should prompt a call.</p>'''),
 ], ['palpitations','palpitations_tests','arrhythmia_tests','arrhythmia_types','pvc','holter','event','af_diagnosis'], ['What is the most likely explanation for my symptoms?','Which monitor and recording duration fit how often my episodes happen?','Do I need blood tests, an echo or an exercise test, and why?','Were my usual symptoms captured, and what rhythm occurred at that time?','Are any medicines, supplements or activities contributing?','When will we review results, and what should I do if symptoms return?'], ['tests/rhythm-monitor.html','tests/echocardiogram.html','articles/afib.html'], updated='2026-09-09')

page('articles/hypertension.html', 'High Blood Pressure', 'Blood pressure',
 'Good technique and a useful record help you and your clinician make sense of your blood pressure.', [
 ('understanding','What the numbers mean', '''<p>Blood pressure is the force of blood against artery walls. The top number, systolic, measures pressure during a heartbeat; the bottom number, diastolic, measures pressure between beats. Either number can be high. Hypertension often causes no symptoms, so measuring it matters.</p><p>A diagnosis uses repeated, properly measured readings and your clinical context. Home measurements can help identify a difference between office and everyday blood pressure.</p>'''),
 ('technique','How to measure at home', '''<ol><li>Use a validated upper-arm monitor with a cuff that fits. Bring it to an appointment to check technique and accuracy.</li><li>Avoid exercise, nicotine and caffeine for 30 minutes beforehand. Empty your bladder.</li><li>Sit quietly for at least five minutes, with back supported, feet flat and legs uncrossed.</li><li>Place the cuff on bare skin and support your arm at heart level. Stay quiet while measuring.</li><li>Take two readings one minute apart. Record both systolic and diastolic numbers from both readings; do not select only the lowest.</li></ol>'''),
 ('frequency','How often should I check?', '''<p>Agree on a schedule with your clinician. When establishing a baseline or reviewing a medication change, a short structured series is often useful: two readings in the morning and two in the evening for several days, commonly seven. Once BP is stable, your clinician may recommend less frequent checks.</p><p>Average readings help identify a pattern. They do not replace attention to symptoms or a very high reading. You do not need to wait 12 weeks to contact your clinician or make a treatment decision together.</p><p><a href="../downloads/BP-Log-Template.pdf">Download a BP log</a> or record individual measurements in <a href="../app/">My Heart Health Tracker</a>.</p>'''),
 ('treatment','Treatment and your personal target', '''<p>Food choices, activity, sleep, limiting sodium and alcohol, and medication can all help. Your target and treatment depend on your overall risk, other conditions, side effects and preferences. Many people need more than one medication.</p><p>Keep an up-to-date medication list. Ask what to do if you miss a dose or feel dizzy. Do not change or stop a medicine based only on a home reading without following your care plan.</p>'''),
 ('when-to-seek-care','When to seek care', '''<div class="care-callout"><p><strong>If systolic BP is above 180 or diastolic BP is above 120:</strong> if you have chest pain, shortness of breath, new weakness, vision changes or trouble speaking, call 911. Do not delay emergency care to collect more readings.</p><p>If you have no concerning symptoms, wait at least one minute and repeat the measurement. If it remains this high, contact your healthcare professional immediately. Severe symptoms need urgent evaluation even when BP is below these numbers.</p></div><p>For a persistent rise in usual readings, medication problems or recurrent lightheadedness, contact your care team according to your agreed plan.</p>'''),
 ], ['bp','bpweek','bp25'], ['What is my BP target?','What schedule should I use, and when should I send my readings?','Which readings or symptoms mean I should call?'], ['tests/echocardiogram.html','cardiac-longevity.html'])

page('articles/statins.html', 'Statins: Benefits, Symptoms, and Options', 'Cholesterol',
 'Lowering cholesterol should come with a clear explanation of the benefit and a plan for any symptoms.', [
 ('benefit','Why a statin may be recommended', '''<p>Statins lower LDL cholesterol and reduce the chance of cardiovascular events in people who are likely to benefit. The expected benefit depends on your starting risk, previous heart or vascular disease, cholesterol levels and how much LDL is lowered.</p><p>Your clinician may also discuss family history, lipoprotein(a), diabetes, kidney disease or a calcium score. A treatment decision is a conversation about your individual risk and priorities.</p>'''),
 ('symptoms','Take symptoms seriously', '''<p>Muscle aches or weakness deserve a careful review. Symptoms may be caused by a statin, another condition, an interaction, exercise or several factors together. Muscle symptoms can occur even with a normal creatine kinase (CK) blood test.</p><p>Record what you feel, when it began and which medicines or supplements you take. Your clinician may suggest a supervised pause, a different dose or statin, or another cholesterol medicine. Do not design your own dose-escalation schedule.</p>'''),
 ('samson','What SAMSON actually studied', '''<p>The SAMSON trial enrolled 60 people who had stopped statins because of symptoms. Participants went through months taking atorvastatin 20 mg, placebo tablets, or no tablets. The full report appeared in <em>JACC</em> in 2021.</p><p>In this selected group, symptom scores were similar during statin and placebo months and lower during no-tablet months. The study helps explain how taking a tablet and expecting symptoms can contribute to how people feel. It does not prove that an individual patient's symptoms are imaginary or that statins never cause adverse effects. SAMSON did not test CoQ10.</p>'''),
 ('options','Finding a treatment you can tolerate', '''<p>Options include changing the statin, lowering the dose, adjusting the schedule under supervision, or adding or using a nonstatin medicine. Your clinician will consider how much LDL lowering you need and the evidence, cost and practicalities of each option.</p><p>Statins can modestly increase diabetes risk in some people; discuss this alongside their expected cardiovascular benefit. Severe muscle injury and serious liver injury are uncommon. Supplements are not a substitute for an individualized treatment plan.</p>'''),
 ('when-to-seek-care','When to get help', '''<p>Contact your clinician promptly for new or persistent muscle symptoms. Seek urgent medical attention for severe muscle weakness or pain with dark urine, or yellowing of the skin or eyes. For difficulty breathing or signs of a serious allergic reaction, call 911.</p>'''),
 ], ['lipid26','samson','intolerance'], ['How much benefit should I expect?','What LDL goal fits my risk?','What is our plan if I develop symptoms?'], ['articles/calcium-score.html','blog/statin-controversy.html'])

page('articles/calcium-score.html', 'Understanding Your Calcium Score', 'Prevention',
 'A coronary calcium score can help personalize prevention. It is one part of your risk assessment.', [
 ('what-it-measures','What the scan measures', '''<p>A coronary artery calcium (CAC) scan is a noncontrast CT scan that measures calcified plaque in the heart arteries. It uses a small amount of radiation. The result is usually reported as an Agatston score, sometimes with a percentile for people of similar age and sex.</p><p>A calcium score does not measure the percentage of narrowing in an artery. It also does not show all noncalcified plaque.</p>'''),
 ('results','Making sense of your result', '''<div class="table-scroll"><table><caption>General meaning of a CAC result</caption><thead><tr><th>Score</th><th>What it tells us</th></tr></thead><tbody><tr><td>0</td><td>No calcified plaque detected. Often reassuring for near-term risk, but it does not exclude all plaque or explain away symptoms.</td></tr><tr><td>1-99</td><td>Calcified plaque is present. Discuss prevention in the context of your age and other risk factors.</td></tr><tr><td>100-299</td><td>A larger plaque burden that strengthens the case for intensive risk-factor management.</td></tr><tr><td>300 or higher</td><td>A substantial plaque burden. Make a clear prevention and follow-up plan with your clinician.</td></tr></tbody></table></div>'''),
 ('decisions','What might change afterward?', '''<p>The result may help settle an uncertain decision about cholesterol-lowering treatment. Current guidance uses overall cardiovascular risk and the amount of calcium to inform LDL goals. A zero score does not automatically remove the need for treatment, especially with conditions such as diabetes, very high LDL or a strong family history.</p><p><strong>Do not start aspirin because of the score alone.</strong> Its possible benefit must be weighed against bleeding risk, age and overall cardiovascular risk. If aspirin is already prescribed, discuss changes with the prescriber.</p>'''),
 ('limits','Who needs a different test?', '''<p>CAC is mainly a prevention tool for selected people without symptoms. Chest symptoms may require a different assessment, such as a <a href="../tests/stress-test.html">stress test</a> or <a href="../tests/coronary-cta.html">coronary CTA</a>, depending on the situation.</p><p>Repeating CAC is not a routine way to measure whether a statin is working. Your clinician can explain whether another scan would change care. Ask the imaging center about cost and coverage before scheduling.</p>'''),
 ('when-to-seek-care','When symptoms change the plan', '''<p>New severe chest discomfort, trouble breathing, fainting or stroke symptoms warrant emergency evaluation. Call 911; do not wait for a screening scan or a routine results visit. Discuss new, less urgent symptoms with your clinician even if your calcium score was zero.</p>'''),
 ], ['cac','lipid26','aspirin','cacaspirin'], ['How does my score change my prevention plan?','What cholesterol goal is right for me?','Would another test change what we do?'], ['tests/calcium-score.html','articles/statins.html','tests/coronary-cta.html'])

page('articles/afib.html', 'Atrial Fibrillation (AFib)', 'Heart rhythm',
 'AFib care addresses how you feel, your heart rhythm, and your personal risk of stroke.', [
 ('understanding','What is AFib?', '''<p>AFib is a rhythm in which the upper heart chambers activate in a disorganized way. The pulse is often irregular and may be fast. Some people notice fluttering, tiredness or breathlessness; others have no symptoms.</p><p>An ECG recording is used to confirm the rhythm. If episodes come and go, a <a href="../tests/rhythm-monitor.html">wearable monitor</a> can help capture them. A watch notification is a reason to discuss testing, not a complete diagnosis by itself.</p>'''),
 ('treatment','Three parts of treatment', '''<ul><li><strong>Stroke prevention:</strong> your clinician estimates your stroke risk and considers whether an anticoagulant is appropriate. Aspirin is not an equivalent substitute. Bleeding history, kidney function, other medicines and valve conditions matter.</li><li><strong>Rate control:</strong> medicines can slow a fast heart rate.</li><li><strong>Rhythm control:</strong> cardioversion, medicines or catheter ablation may help restore or maintain a usual rhythm. Earlier rhythm treatment may be useful for selected people.</li></ul><p>Feeling better after cardioversion or ablation does not automatically mean it is safe to stop an anticoagulant. Make that decision with your clinician based on stroke risk.</p>'''),
 ('daily-life','What you can do', '''<p>Discuss a realistic activity plan, blood pressure control, sleep apnea evaluation when appropriate, and reducing or avoiding alcohol. If weight loss is recommended, ask for a sustainable plan. Keep a list of medicines and bring a record of symptoms and pulse readings to appointments.</p><p>Tell your care team about missed doses, side effects and cost barriers. Before procedures or dental work, ask the prescribing clinician for an anticoagulation plan.</p>'''),
 ('when-to-seek-care','When to seek care', '''<p>Call 911 for signs of stroke, such as a drooping face, arm weakness or trouble speaking, or for severe chest pain, fainting or severe breathing difficulty. If you take an anticoagulant, major bleeding or a significant head injury needs urgent assessment.</p><p>For sustained palpitations, a change in your usual symptoms or medication concerns, follow the contact plan from your care team. A monitor is not a substitute for emergency care.</p>'''),
 ], ['af','event'], ['What is my stroke risk, and do I need an anticoagulant?','Should we discuss rate control, rhythm control or both?','What should I do during an episode?'], ['tests/rhythm-monitor.html','tests/echocardiogram.html'])

page('articles/heart-failure.html', 'Living With Heart Failure', 'Heart failure',
 'Heart failure means the heart is not meeting the body’s needs normally. A clear treatment and follow-up plan can help.', [
 ('understanding','What does the diagnosis mean?', '''<p>Heart failure can involve reduced pumping strength, abnormal filling, or both. It can occur with a reduced or a preserved <a href="../tests/echocardiogram.html">ejection fraction (EF)</a>. EF is one measurement, not the whole diagnosis.</p><p>Breathlessness, leg swelling, fatigue and difficulty lying flat can occur, but these symptoms have other possible causes. Clinicians combine the history, examination, blood tests and imaging to make the diagnosis.</p>'''),
 ('treatment','Treatment depends on your type of heart failure', '''<p>For heart failure with reduced EF, several medicine groups can improve outcomes: an ARNI, ACE inhibitor or ARB; an evidence-based beta blocker; a mineralocorticoid receptor antagonist; and an SGLT2 inhibitor. The combination and doses depend on blood pressure, kidney function, potassium and tolerance.</p><p>For preserved or mildly reduced EF, SGLT2 inhibitors and management of contributing conditions can be helpful. Diuretics may relieve congestion. Some people benefit from devices or specialist treatments. Ask what each medicine is intended to do.</p><p>An improved EF is encouraging, but do not stop treatment just because a later scan looks better.</p>'''),
 ('home-plan','Build a home plan with your team', '''<ul><li>Know which symptoms and weight changes should trigger a call. Use the specific thresholds your team gives you.</li><li>If daily weights are recommended, use the same scale and similar conditions each morning.</li><li>Discuss sodium and fluid advice for your situation; avoid applying another person's limits to yourself.</li><li>Ask about safe activity and <a href="cardiac-rehabilitation.html">cardiac rehabilitation</a>.</li><li>Keep an updated medicine list and a plan for follow-up blood tests.</li></ul><p><a href="../app/">My Heart Health Tracker</a> can help you keep a record. It does not send readings to your care team or generate clinical alerts.</p>'''),
 ('when-to-seek-care','When to seek care', '''<p>Call 911 for severe shortness of breath at rest, chest pain, fainting or new confusion. Contact your care team promptly for worsening swelling, new difficulty lying flat, unexpected weight gain according to your plan, or a clear fall in your ability to do usual activities.</p><p>Do not take extra diuretic doses unless your clinician has given you a specific action plan.</p>'''),
 ], ['hf','hfpatient','ef'], ['Which type of heart failure do I have?','What changes should prompt a call, and whom should I call?','Which medicines, blood tests and activity goals are part of my plan?'], ['tests/echocardiogram.html','articles/cardiac-rehabilitation.html','app/index.html'])

page('articles/cad.html', 'Coronary Artery Disease', 'Heart arteries',
 'Treatment aims to reduce future risk and help you manage symptoms and everyday activity.', [
 ('understanding','What is coronary artery disease?', '''<p>Coronary artery disease develops when plaque builds up in the arteries supplying the heart muscle. Plaque may narrow an artery, and a disrupted plaque can trigger a clot and a heart attack. The amount of narrowing and future risk are related, but they are not the same measurement.</p><p>Some people have no symptoms. Others develop chest pressure or breathlessness with exertion. New or changing symptoms deserve assessment.</p>'''),
 ('testing','Why different tests are used', '''<p>A <a href="../tests/calcium-score.html">calcium score</a> helps with selected prevention decisions. A <a href="../tests/coronary-cta.html">coronary CTA</a> looks at plaque and artery narrowing. A <a href="../tests/stress-test.html">stress test</a> assesses the response to exertion or medication-induced stress. Your symptoms, previous results and other conditions determine which test is useful.</p><p>A normal test cannot guarantee that a heart problem will never occur. Tell your clinician when symptoms change rather than relying only on an older result.</p>'''),
 ('treatment','What treatment may include', '''<p>Cholesterol-lowering treatment, blood pressure management, avoiding tobacco, appropriate activity and food choices all matter. Medicines may also help angina. Antiplatelet treatment depends on your history and bleeding risk; follow the plan from your clinician, particularly after a stent.</p><p>Stents or bypass surgery can be appropriate for certain symptoms and patterns of disease. They do not remove the need for ongoing prevention. In stable disease, the best next step is individualized.</p><p>Ask whether you qualify for <a href="cardiac-rehabilitation.html">cardiac rehabilitation</a>. Bring up treatment cost, symptoms and practical barriers so the plan is workable.</p>'''),
 ('when-to-seek-care','When to seek care', '''<p>Call 911 for new severe chest pressure or discomfort lasting more than a few minutes or recurring, especially with sweating, nausea, breathlessness or pain spreading to the arm, jaw or back. Heart attack symptoms can vary. Do not drive yourself or wait for an online response.</p><p>For familiar angina, follow your prescribed action plan. Increasing frequency, symptoms at less activity or symptoms at rest need prompt medical evaluation.</p>'''),
 ], ['cad','lipid26','stress'], ['What does my diagnosis mean for my future risk?','What is my plan for chest symptoms?','What are my cholesterol, BP and activity goals?'], ['tests/stress-test.html','tests/coronary-cta.html','articles/statins.html'])

page('articles/aortic-stenosis.html', 'Aortic Stenosis and Valve Replacement', 'Heart valves',
 'A narrowed aortic valve needs the right combination of follow-up, symptom assessment and timely treatment.', [
 ('understanding','What is aortic stenosis?', '''<p>The aortic valve opens to let blood leave the heart. Aortic stenosis means the opening has become narrowed, often because the valve has thickened or calcified. Some people are born with a two-leaflet, or bicuspid, valve that can develop problems earlier.</p><p>An <a href="../tests/echocardiogram.html">echocardiogram</a> measures valve function and the heart's response. Terms such as mild, moderate and severe describe findings that must be interpreted together.</p>'''),
 ('follow-up','Why follow-up matters', '''<p>Mild or moderate disease is often followed with periodic visits and echocardiograms. Your clinician sets the interval. Report new breathlessness, chest discomfort, dizziness, fainting or a decline in exercise capacity rather than waiting for the next planned scan.</p><p>Medication can treat associated conditions, but it does not reliably reverse a severely narrowed valve. In severe disease, the timing of intervention depends on symptoms, heart function and other findings.</p>'''),
 ('options','TAVR and surgery', '''<p>Transcatheter aortic valve replacement (TAVR, also called TAVI) places a tissue valve through a catheter, often via an artery in the groin. Surgical aortic valve replacement is an operation to replace the valve.</p><p>A valve team considers your anatomy, age, health, expected valve durability, recovery needs and preferences. TAVR is not the best option for everyone. Both approaches have potential risks, including stroke, bleeding, infection and the possible need for a pacemaker; your team will explain the risks that apply to you.</p><p>After replacement, follow-up, medication instructions and dental care remain important. Ask for a written plan.</p>'''),
 ('when-to-seek-care','When to seek care', '''<p>Call 911 for severe chest pain, fainting or severe breathing difficulty. New exertional symptoms should prompt contact with your care team. Ask about activity limits, especially if the valve narrowing is severe; avoid starting strenuous exercise without guidance.</p>'''),
 ], ['valve','tavr','valvetests'], ['How severe is my valve narrowing?','Which symptoms should I report, and when is my next echo?','If replacement is needed, how do we choose between TAVR and surgery?'], ['tests/echocardiogram.html','articles/exercise-after-diagnosis.html'])

page('tests/echocardiogram.html', 'Your Echocardiogram', 'Understanding your tests',
 'An echo uses ultrasound to look at the heart muscle, chambers and valves.', [
 ('why','Why it was ordered', '''<p>An echo can help evaluate a murmur, breathlessness, swelling, heart muscle function or known valve disease. It answers a different question from an ECG, which records electrical activity.</p>'''),
 ('expect','What to expect', '''<p>For a standard transthoracic echo, you lie on an exam table while a sonographer uses gel and a probe on your chest. It does not use ionizing radiation. Some studies use an IV ultrasound-enhancing agent. A transesophageal echo (TEE) is a different procedure with separate preparation and sedation instructions.</p>'''),
 ('results','Words you may see in the report', '''<ul><li><strong>Ejection fraction (EF):</strong> the percentage of blood the left ventricle ejects with a beat. About 55-70% is a commonly used normal range, with variation by lab and method. It is not a percentage of how much of the heart is working.</li><li><strong>Regurgitation:</strong> backward leakage through a valve. Trace or mild leakage is often followed rather than treated immediately; the valve involved, symptoms and other findings matter.</li><li><strong>Stenosis:</strong> narrowing of a valve.</li><li><strong>Diastolic function:</strong> how the heart relaxes and fills. A report finding alone does not establish heart failure.</li></ul><p>A preserved EF does not exclude heart failure. Small differences between scans can reflect measurement variation as well as real change.</p>'''),
 ('next','What happens next', '''<p>Ask the ordering clinician to explain the important findings and whether they change treatment or follow-up. A standard resting echo does not show every coronary artery blockage. If symptoms continue, more evaluation may be needed.</p>'''),
 ], ['echo','ef','valvetests'], ['What are the important findings in my echo?','Does any valve finding need follow-up?','Does this result explain my symptoms, and what happens next?'], ['articles/heart-failure.html','articles/aortic-stenosis.html'], 'echo-summary.pdf')

page('tests/rhythm-monitor.html', 'Your Zio or Rhythm Monitor', 'Understanding your tests',
 'A wearable ECG monitor records your rhythm during everyday life so symptoms and heartbeats can be compared.', [
 ('why','Why wear a monitor?', '''<p>Palpitations, dizziness or fainting can come and go. A short office ECG may miss an episode. A patch, Holter or event monitor records for the period your clinician selects. Different devices record or transmit data differently.</p>'''),
 ('wearing','While wearing it', '''<p>Follow the instructions for your exact device, including wear time, showering, exercise and return shipping. Log the time of symptoms and what you were doing. If instructed, press the event button as well. Contact the device service or ordering office for a loose patch, skin problems or questions about use.</p><p>The <a href="https://www.irhythmtech.com/us/en/solutions-services/irhythm-service/myzio-patient-app">manufacturer's MyZio information</a> explains symptom logging for Zio users. Recording a symptom is not the same as requesting urgent help.</p>'''),
 ('results','Understanding common findings', '''<ul><li><strong>Sinus rhythm:</strong> a rhythm starting from the heart's usual pacemaker.</li><li><strong>PACs and PVCs:</strong> early beats from the upper or lower chambers. Their frequency, pattern, your symptoms and heart structure affect their significance.</li><li><strong>Burden:</strong> how much of the recording contains a particular rhythm or type of beat.</li><li><strong>Runs or episodes:</strong> groups of beats described by their rhythm, speed and duration. A short report label does not determine treatment by itself.</li></ul>'''),
 ('next','Getting the result', '''<p>Return the device as instructed and ask when and how the report will be reviewed. Your clinician considers the rhythm strips and symptom timing, not just an automated summary. Some monitors are reviewed after they are returned; do not assume yours is watched continuously.</p><p>For severe chest pain, fainting, stroke symptoms or severe breathlessness, call 911 instead of waiting for the monitor or its report.</p>'''),
 ], ['holter','event','pvc','zio'], ['What question is this monitor meant to answer?','How do I log symptoms and return my device?','Which findings matter, and when will we review the results?'], ['articles/palpitations.html','articles/afib.html','tests/echocardiogram.html'], 'rhythm-monitor-summary.pdf')

page('tests/calcium-score.html', 'Your Coronary Calcium Scan', 'Understanding your tests',
 'This scan helps refine a prevention decision by looking for calcified plaque.', [
 ('why','Why it was ordered', '''<p>A clinician may recommend a coronary artery calcium (CAC) scan when its result could help decide how to manage future cardiovascular risk, including an uncertain cholesterol-treatment decision. It is not a universal screening test for everyone.</p>'''),
 ('expect','Before and during the scan', '''<p>A CAC scan uses CT and usually does not require IV contrast. Follow the imaging center's preparation instructions, and tell them if you may be pregnant. Ask about cost and insurance coverage in advance.</p>'''),
 ('results','What your score means', '''<p>A score of zero means no calcified plaque was detected. A positive score means calcified plaque is present; a higher score generally indicates more plaque and greater risk. Your age, other risk factors and sometimes the percentile help put it in context.</p><p>A zero score does not exclude noncalcified plaque or guarantee that symptoms are harmless. A positive score is not the percentage of blockage in an artery.</p>'''),
 ('next','What happens next', '''<p>Review the score alongside your cholesterol, BP, family history and other conditions. Agree on treatment goals and follow-up. Do not start aspirin, stop a statin or schedule repeat scans based only on the number.</p><p><a href="../articles/calcium-score.html">Read the full calcium-score guide</a> for prevention decisions and limitations. New severe chest symptoms need emergency assessment, not a screening scan.</p>'''),
 ], ['cac','lipid26','aspirin'], ['Would this scan change my treatment?','What does the result mean for my personal risk?','What is our prevention and follow-up plan?'], ['articles/calcium-score.html','articles/statins.html','tests/coronary-cta.html'], 'calcium-score-summary.pdf')

page('tests/stress-test.html', 'Your Stress Test', 'Understanding your tests',
 'A stress test looks at how your heart responds when it needs to work harder.', [
 ('why','Why it was ordered', '''<p>Stress testing can help assess exertional symptoms, possible reduced blood flow to heart muscle, exercise capacity or selected rhythm concerns. The type of test depends on the question, your ability to exercise and your baseline ECG.</p>'''),
 ('types','Exercise, echo and nuclear tests', '''<p>You may walk on a treadmill or use a bicycle while staff monitor symptoms, ECG, heart rate and blood pressure. Some tests add ultrasound images (stress echo) or a radioactive tracer and camera (nuclear perfusion imaging).</p><p>If exercise is not suitable, medication can create the stress needed for imaging. These tests differ, so the preparation and time required vary.</p>'''),
 ('prepare','How to prepare', '''<p>Get instructions from the testing center about food, caffeine, clothing and medicines. Some medications and caffeine can affect particular tests. <strong>Do not hold prescribed medicines unless the team specifically tells you to.</strong> Tell them about breathing problems, pregnancy possibility, medication reactions and difficulty walking.</p>'''),
 ('results','What the result can tell you', '''<p>A normal result can be reassuring about the question tested, but it does not exclude all plaque or every cause of chest symptoms. An abnormal or inconclusive result may lead to a treatment change or further testing. Artifacts and test limitations can affect interpretation.</p>'''),
 ('next','What happens next', '''<p>Ask whether the test was adequate, what the findings mean, and whether activity or treatment should change. Do not wait for a scheduled test if you develop severe chest discomfort, fainting or severe breathing difficulty; call 911.</p>'''),
 ], ['stress','nuclear','cad'], ['Which type of stress test am I having, and why?','What exact preparation and medication instructions should I follow?','Does the result change my activity or treatment?'], ['articles/cad.html','tests/coronary-cta.html'], 'stress-test-summary.pdf')

page('tests/coronary-cta.html', 'Your Coronary CT Angiogram', 'Understanding your tests',
 'Coronary CTA uses CT and IV contrast to look at the heart arteries and plaque.', [
 ('why','Why it was ordered', '''<p>Coronary CT angiography (CCTA) can help evaluate selected patients with possible coronary disease. It shows artery anatomy, including calcified and noncalcified plaque, and estimates narrowing. A calcium scan and CCTA answer different questions.</p>'''),
 ('prepare','Before your appointment', '''<p>Follow the center's instructions on food, caffeine and medicines. Tell the team about previous reactions to iodinated contrast, kidney disease, pregnancy possibility and all medicines, including erectile-dysfunction drugs. Blood tests may be needed.</p><p>The team may use medication to slow the heart rate or nitroglycerin to improve artery imaging when appropriate. Do not make those medication changes yourself.</p>'''),
 ('expect','During the scan', '''<p>An IV delivers contrast while you lie on a CT table and follow short breath-hold instructions. Contrast can cause a brief warm feeling. The test involves radiation and potential contrast-related risks, which your team will weigh against its expected benefit.</p>'''),
 ('results','Understanding your report', '''<p>The report may describe plaque, the location and degree of narrowing, and whether image quality limits interpretation. Calcium, motion or other factors can make some segments difficult to assess.</p><p>An anatomic narrowing does not always tell us its effect on blood flow. Depending on the findings, further functional assessment or invasive angiography may be considered. Not every plaque finding requires a procedure.</p>'''),
 ('next','What happens next', '''<p>Review the result with the ordering clinician and agree on prevention, symptom treatment and any additional testing. Contact the imaging team for concerns after contrast. Severe chest symptoms, trouble breathing or fainting require urgent assessment; call 911.</p>'''),
 ], ['cta','cad','lipid26'], ['What question will CCTA answer in my case?','Do my kidneys, contrast history or medicines affect preparation?','What do the findings change about my care?'], ['tests/calcium-score.html','tests/stress-test.html','articles/cad.html'], 'coronary-cta-summary.pdf')

page('articles/getting-started-exercise.html', 'Getting Started With Exercise', 'Exercise and recovery',
 'Choose a starting point you can repeat. Small amounts of movement can be the beginning of a lasting habit.', [
 ('start','Start with a manageable routine', '''<p>If you feel well and have no condition that limits activity, a short walk or another comfortable activity can be a reasonable starting point. For example, choose five or ten minutes at a time you can repeat. Increase gradually as it feels manageable.</p><p>The usual adult goal is at least 150 minutes of moderate aerobic activity per week, or 75 minutes of vigorous activity, plus muscle-strengthening activity on at least two days. This is a goal to work toward, not an entry requirement.</p>'''),
 ('intensity','How hard should it feel?', '''<p>During moderate activity, you should generally be able to talk, even though you are breathing harder. Warm up and cool down at an easy pace. A watch heart-rate target is not a universal prescription, especially if you take a beta blocker or have an arrhythmia.</p><p>Build time and consistency before making activity much harder. Consider walking, cycling, swimming or a chair-based option that fits your mobility and surroundings. Break up long periods of sitting.</p>'''),
 ('individual','When you need an individual plan', '''<p>If you have known heart disease, new exercise symptoms, a recent procedure or a plan for vigorous training, discuss appropriate limits and progression with your clinician. Read <a href="exercise-after-diagnosis.html">returning to activity after a diagnosis</a>.</p><p>Training for an endurance event or HYROX involves different demands from starting a walking routine. Your medical history and the demands of the event should guide that conversation.</p>'''),
 ('symptoms','Listen to warning symptoms', '''<p>Stop if you develop chest discomfort, marked dizziness, unusual breathlessness or palpitations that make you feel unwell. Severe or persistent chest symptoms, fainting or severe trouble breathing warrant calling 911. Discuss new exercise-related symptoms before resuming the activity that caused them.</p>'''),
 ], ['eight','activity','exerciseplan'], ['What is a realistic starting goal for me?','Do I have any activity restrictions?','How should I increase time or intensity?'], ['articles/exercise-after-diagnosis.html','articles/cardiac-rehabilitation.html','cardiac-longevity.html'])

page('articles/exercise-after-diagnosis.html', 'Returning to Exercise After a Heart Diagnosis', 'Exercise and recovery',
 'A safe return to activity starts with a plan for your condition, treatment and recovery.', [
 ('plan','Get a clear starting plan', '''<p>After a heart attack, new heart-failure diagnosis, valve problem or cardiac procedure, ask your team what activities you can begin and what to avoid. Restrictions depend on your condition and, after a procedure, healing of an incision or access site.</p><p>Ask whether you should be referred to <a href="cardiac-rehabilitation.html">cardiac rehabilitation</a>. The team may recommend additional evaluation before you resume exercise.</p>'''),
 ('progress','Progress one step at a time', '''<p>Once cleared, begin at the level your team recommends. Short, easy sessions may be more manageable than one long effort. Build duration and frequency before increasing intensity. Include a warm-up and cool-down.</p><p>Write down how long you were active, how it felt, and any symptoms. Discuss goals such as lifting weights, returning to work, running or competition individually. Recovery timelines are not identical for everyone.</p>'''),
 ('medicines','Account for treatment and symptoms', '''<p>Medicines can change heart rate, blood pressure and fluid balance. Ask how to judge exertion, how to manage heat, and what hydration advice fits your condition. For heart failure, follow your own fluid plan. Carry prescribed rescue medicine and follow its instructions if you have one.</p><p>Do not push through symptoms to reach a watch target or a previous training pace. Active heart inflammation, decompensated heart failure, uncontrolled rhythm problems or severe symptomatic valve disease may require exercise to be deferred.</p>'''),
 ('symptoms','When to stop and get help', '''<p>Stop activity for chest pressure, significant dizziness, unusual breathlessness or a racing heartbeat with feeling unwell. Call 911 for severe or persistent chest symptoms, fainting or severe breathing difficulty. Contact your team about milder new symptoms before progressing.</p>'''),
 ], ['restart','exerciseplan','activity'], ['What can I do now, and what must wait?','Should I join cardiac rehabilitation?','Which symptoms or changes mean I should stop and call?'], ['articles/cardiac-rehabilitation.html','articles/heart-failure.html','articles/getting-started-exercise.html'])

page('articles/cardiac-rehabilitation.html', 'Cardiac Rehabilitation', 'Exercise and recovery',
 'Cardiac rehab combines supervised activity, education and support to help you recover and build confidence.', [
 ('program','What happens in cardiac rehab?', '''<p>A cardiac rehabilitation program helps you develop a safe activity routine, understand your medicines and risk factors, and work on food choices, tobacco cessation and emotional well-being. It is more than an exercise class.</p><p>Your team assesses your needs and sets goals with you. Sessions may involve monitoring and individualized exercise progression as well as practical education.</p>'''),
 ('eligibility','Who may be eligible?', '''<p>People recovering from a heart attack, stent procedure, bypass surgery or certain valve procedures may qualify. Some people with stable heart failure also qualify. Clinical suitability and insurance coverage are separate questions; confirm both with the program and your care team.</p>'''),
 ('access','Making it work in real life', '''<p>Ask your clinician for a referral and whom to call to schedule. Discuss transportation, work hours, cost and caregiving needs. If attending in person is difficult, ask about available home-based or hybrid options that are appropriate for you.</p><p>Bring your medication list and questions to the first visit. Tell the team about new symptoms, medication changes and what you want to be able to do again.</p>'''),
 ('after','What happens after the program?', '''<p>Work with the team on a sustainable activity and prevention plan for home. You can keep a simple activity record and review progress at follow-up appointments. Confidence often grows from having a plan you understand and can repeat.</p><p>Do not wait for a rehab session to report worsening symptoms. Severe chest pain, fainting or severe breathing difficulty warrant calling 911.</p>'''),
 ], ['rehab','rehabeligible','cad'], ['Am I eligible, and has a referral been sent?','What will my insurance cover?','What options fit my schedule and recovery goals?'], ['articles/exercise-after-diagnosis.html','articles/heart-failure.html'])

page('cardiac-longevity.html', 'Cardiac Longevity', 'Prevention and everyday health',
 'Build habits and a prevention plan that support the activities and people that matter to you.', [
 ('habits','The foundations of heart health', '''<p>The American Heart Association's <strong>Life's Essential 8</strong> framework includes eating well, being active, avoiding nicotine, healthy sleep, managing weight, and managing cholesterol, blood sugar and blood pressure. These are connected parts of prevention.</p><p>Choose a practical first step: a short walk, a regular sleep schedule, replacing one high-sodium meal, or reviewing your medication list. Social connection and help with stress can support the plan too.</p>'''),
 ('targets','Your numbers need context', '''<p>There is no single cholesterol or apoB goal for everyone. Your clinician considers existing vascular disease, overall risk, other conditions and treatment tolerance. The 2026 dyslipidemia guideline recommends measuring lipoprotein(a) at least once in adulthood and using apoB selectively to refine risk and treatment.</p><p>Agree on BP goals and a measurement schedule with your clinician. Keep both numbers from each reading. Averages are useful, but symptoms and very high readings still need attention.</p>'''),
 ('activity','Move in a way you can sustain', '''<p>Start with activity you enjoy and can repeat. Build aerobic activity and strength gradually. People returning after a cardiac diagnosis or procedure need an individualized plan. Exercise supports prevention, but it does not replace medicines or procedures that are indicated.</p><p>Read the <a href="articles/getting-started-exercise.html">getting started guide</a>, <a href="articles/exercise-after-diagnosis.html">return-to-exercise guide</a> and <a href="articles/cardiac-rehabilitation.html">cardiac rehab guide</a>.</p>'''),
 ('plan','Make the next visit useful', '''<ul><li>Bring your medication list and any requested BP or weight records.</li><li>Pick one health goal that matters in everyday life.</li><li>Discuss family history and whether additional risk testing would change treatment.</li><li>Agree on follow-up, who reviews results, and when to call sooner.</li></ul><p>Focus on steady progress. No checklist can promise a specific number of extra years or eliminate cardiovascular risk.</p>'''),
 ], ['eight','lipid26','lipidgoals','bp'], ['Which prevention goals matter most for me?','Would Lp(a), apoB or a calcium score change my care?','What is one change I can sustain this month?'], ['articles/hypertension.html','articles/statins.html','articles/getting-started-exercise.html'])

page('blog/blood-pressure-at-home.html', 'Blood Pressure at Home: Make the Readings Useful', 'Dr. Pollock’s Notes',
 'A calm, repeatable routine is more helpful than chasing a single number.', [
 ('routine','Build a repeatable routine', '''<p>Home BP becomes easier to interpret when the technique stays consistent: the right cuff, a supported seated position, a quiet rest, and two readings one minute apart. Keep both numbers from both readings.</p><p>Agree on frequency with your clinician. A structured series can be useful for diagnosis or a medication review; stable follow-up may need a lighter schedule. Checking repeatedly out of worry can make the process harder, so ask for a clear plan.</p>'''),
 ('meaning','Use the record to guide a conversation', '''<p>A pattern can tell us more than an isolated reading, but an average must not hide an urgent problem. Severe symptoms need emergency care. A persistent reading above 180 systolic or 120 diastolic needs prompt action as described in the <a href="../articles/hypertension.html#when-to-seek-care">BP guide</a>.</p><p>Bring your readings and monitor to your next visit. Ask what changes should prompt an earlier call. The goal is information you can use together.</p>'''),
 ], ['bp','bpweek'], ['What monitoring schedule should I follow?','When and how should I share my readings?'], ['articles/hypertension.html','app/index.html'])

page('blog/exercise-is-the-best-medicine.html', 'Exercise: Start Where You Are', 'Dr. Pollock’s Notes',
 'A routine you can repeat is a useful place to begin.', [
 ('begin','Make the first step small enough to do', '''<p>Getting active does not have to start with a race, gym membership or a dramatic training plan. It can begin with a walk after lunch, standing up more often, or a short activity you enjoy.</p><p>Choose a realistic time and place. If you feel well, build gradually. If you have a new diagnosis, recent procedure or exercise symptoms, ask your care team for a plan before increasing activity.</p>'''),
 ('progress','Measure progress in everyday life', '''<p>Notice whether usual activities feel easier, whether you are becoming more consistent, and whether you enjoy the routine. Those changes matter alongside minutes, pace and watch data.</p><p>Use the <a href="../articles/getting-started-exercise.html">starting exercise guide</a> for practical steps, or the <a href="../articles/exercise-after-diagnosis.html">return-to-exercise guide</a> if you are recovering. Cardiac rehabilitation can provide structure and confidence when you qualify.</p>'''),
 ], ['eight','exerciseplan'], ['What activity feels achievable this week?','Do I need a tailored plan before progressing?'], ['articles/getting-started-exercise.html','articles/cardiac-rehabilitation.html'])

page('blog/statin-controversy.html', 'A Better Conversation About Statins', 'Dr. Pollock’s Notes',
 'A useful treatment discussion includes both the expected benefit and a plan for symptoms.', [
 ('benefit','Ask what the medicine will do for you', '''<p>When a statin is recommended, ask why it fits your situation. A previous heart attack, substantial plaque, diabetes or other risk factors can change the expected benefit. Your treatment should have a goal you understand.</p>'''),
 ('symptoms','Make room for concerns', '''<p>If you develop symptoms, report them. The next step is to work out what is happening and find a treatment you can tolerate. A change in dose or medicine may help; sometimes another cause needs attention.</p><p>SAMSON showed that taking a tablet and expectations about treatment can contribute to symptom burden. It did not show that every patient's symptoms are unrelated to a statin. A careful, respectful review is more useful than dismissing concerns.</p><p>The <a href="../articles/statins.html">statin guide</a> explains the study and the options to discuss with your clinician.</p>'''),
 ], ['samson','intolerance','lipid26'], ['What benefit should I expect from treatment?','What will we do if I develop symptoms?'], ['articles/statins.html','articles/calcium-score.html'])
